"""add project

Revision ID: af14718b4d9d
Revises: 
Create Date: 2021-12-16 18:16:18.203363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af14718b4d9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('data', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'data', 'project', ['project_id'], ['id'])
    op.add_column('parameter_types', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parameter_types', 'project', ['project_id'], ['id'])
    op.drop_column('parameter_types', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter_types', sa.Column('unit', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'parameter_types', type_='foreignkey')
    op.drop_column('parameter_types', 'project_id')
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'project_id')
    op.drop_table('project')
    # ### end Alembic commands ###
